### ISSUE TITLE
Check how could we utilize GTFS data manager

### ISSUE THREAD

**Issue by samuliheljo** [HSLdevcom/openjourneyplanner#41]
https://github.com/conveyal/gtfs-data-manager

**Comment by samuliheljo** [comment]
http://conveyal.com/img/projects/data-tools-deploy.png

**Comment by hannesj** [comment]
http://conveyal.com/blog/2015/01/23/data-management-tools/

**Comment by samuliheljo** [comment]
Moved here: https://github.com/HSLdevcom/openjourneyplanner-data/issues/5
