### ISSUE TITLE
Design fonts and icons

### ISSUE THREAD

**Issue by samuliheljo** [HSLdevcom/openjourneyplanner#57]
- we need two fonts: hsl, general
- We can start by using only general version

**Comment by samuliheljo** [comment]
Missing: stop-icon, stop-icon on map, waiting time

**Comment by samuliheljo** [comment]
Missing: waiting time

**Comment by hannesj** [comment]
Newest icons, including stop, info and waiting included in HSLdevcom/openjourneyplanner-ui#64
